[package]
name = "bevy2048"
version = "0.1.0"
edition = "2021"
description = ""

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.9"
rand = "0.8.3"

[package.metadata.bundle]
identifier = "com.darklichcode.2048"